#define NEXUS_GENERATED_BINDER
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Nexus AOT Binder Code Generator.
//     Package Version: 0.4.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Nexus.Core;
using Nexus.Netcode;

namespace Nexus.Generated
{
    public static class NexusGeneratedBinder
    {

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]
        public static void Initialize()
        {
            NexusDI.RegisterInjector<Nexus.Core.Services.AudioService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.AudioRootProvider = di.Resolve<Nexus.Core.Services.IAudioRootProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.AudioService>(instance =>
            {
                instance.PlayerPrefsService = null;
                instance.AudioRootProvider = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.EconomyService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.NetworkValidator = di.Resolve<Nexus.Core.Services.INetworkEconomyValidator>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.EconomyService>(instance =>
            {
                instance.PlayerPrefsService = null;
                instance.NetworkValidator = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.FeedbackService>((instance, di) =>
            {
                instance.AudioService = di.Resolve<Nexus.Core.Services.IAudioService>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.FeedbackService>(instance =>
            {
                instance.AudioService = null;
                instance.HapticService = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.HapticService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.HapticService>(instance =>
            {
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.LocalizationService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.TableProvider = di.Resolve<Nexus.Core.Services.ILocalizationTableProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.LocalizationService>(instance =>
            {
                instance.PlayerPrefsService = null;
                instance.TableProvider = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.ProgressionService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.ProgressionService>(instance =>
            {
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.SaveThrottler>((instance, di) =>
            {
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
                instance.TimeProvider = di.Resolve<Nexus.Core.Services.ITimeProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.SaveThrottler>(instance =>
            {
                instance.TickService = null;
                instance.TimeProvider = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.WindowManager>((instance, di) =>
            {
                instance.AssetProvider = di.Resolve<Nexus.Core.Services.IUIAssetProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.WindowManager>(instance =>
            {
                instance.AssetProvider = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.CellView>((instance, di) =>
            {
                instance.ThemePalette = di.Resolve<PixelFlow.Data.ThemePaletteAsset>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.CellView>(instance =>
            {
                instance.ThemePalette = null;
                instance.ObstacleService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.DailyCrisisMediator>((instance, di) =>
            {
                instance.DailyCrisisModel = di.Resolve<PixelFlow.Models.IDailyCrisisModel>();
                instance.DailyCrisisService = di.Resolve<PixelFlow.Services.IDailyCrisisService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.DailyCrisisMediator>(instance =>
            {
                instance.DailyCrisisModel = null;
                instance.DailyCrisisService = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.GarageMediator>((instance, di) =>
            {
                instance.InventoryModel = di.Resolve<PixelFlow.Models.IInventoryModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.GarageMediator>(instance =>
            {
                instance.InventoryModel = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.GarageView>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.GarageView>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.GridMediator>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.Logger = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.AudioService = di.Resolve<PixelFlow.Services.IAudioService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.GridMediator>(instance =>
            {
                instance.GridModel = null;
                instance.SettingsModel = null;
                instance.Logger = null;
                instance.AudioService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.GridView>((instance, di) =>
            {
                instance.CameraProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.GridView>(instance =>
            {
                instance.CameraProvider = null;
                instance.LoggerService = null;
                instance.Config = null;
                instance.TickService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.HUDMediator>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.ProgressionService = di.Resolve<PixelFlow.Services.ILevelProgressionService>();
                instance.LocalizationService = di.Resolve<Nexus.Core.Services.ILocalizationService>();
                instance.PowerUpService = di.Resolve<PixelFlow.Services.IPowerUpService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.HUDMediator>(instance =>
            {
                instance.LoggerService = null;
                instance.HintModel = null;
                instance.LevelModel = null;
                instance.SettingsModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.HistoryService = null;
                instance.ProgressionService = null;
                instance.LocalizationService = null;
                instance.PowerUpService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.HUDView>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.HUDView>(instance =>
            {
                instance.LoggerService = null;
                instance.TickService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.MainMenuMediator>((instance, di) =>
            {
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.ProgressModel = di.Resolve<PixelFlow.Models.IProgressModel>();
                instance.InventoryModel = di.Resolve<PixelFlow.Models.IInventoryModel>();
                instance.ProgressionService = di.Resolve<PixelFlow.Services.ILevelProgressionService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.TutorialDriver = di.Resolve<PixelFlow.Services.ITutorialDriver>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.MainMenuMediator>(instance =>
            {
                instance.GameStateModel = null;
                instance.ProgressModel = null;
                instance.InventoryModel = null;
                instance.ProgressionService = null;
                instance.LoggerService = null;
                instance.GridModel = null;
                instance.GameSessionModel = null;
                instance.LevelModel = null;
                instance.PlayerPrefsService = null;
                instance.ObstacleService = null;
                instance.TutorialDriver = null;
                instance.SignalBus = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.MainMenuView>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.MainMenuView>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SettingsMediator>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SettingsMediator>(instance =>
            {
                instance.SettingsModel = null;
                instance.GameStateModel = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SettingsView>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SettingsView>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SoundHandlerMediator>((instance, di) =>
            {
                instance.SoundModel = di.Resolve<PixelFlow.Models.ISoundModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SoundHandlerMediator>(instance =>
            {
                instance.SoundModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SplashMediator>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SplashMediator>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SplashView>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SplashView>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.ThemeHandlerMediator>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.CameraProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.ThemePalette = di.Resolve<PixelFlow.Data.ThemePaletteAsset>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.ThemeHandlerMediator>(instance =>
            {
                instance.SettingsModel = null;
                instance.CameraProvider = null;
                instance.LoggerService = null;
                instance.ThemePalette = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.TutorialView>((instance, di) =>
            {
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.TutorialView>(instance =>
            {
                instance.TickService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.TutorialMediator>((instance, di) =>
            {
                instance.TutorialModel = di.Resolve<PixelFlow.Models.ITutorialModel>();
                instance.TutorialDriver = di.Resolve<PixelFlow.Services.ITutorialDriver>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.TutorialMediator>(instance =>
            {
                instance.TutorialModel = null;
                instance.TutorialDriver = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.AdManagerService>((instance, di) =>
            {
                instance.InventoryModel = di.Resolve<PixelFlow.Models.IInventoryModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.AdManagerService>(instance =>
            {
                instance.InventoryModel = null;
                instance.LoggerService = null;
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.LevelModel = null;
                instance.Config = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.AudioService>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.AudioService>(instance =>
            {
                instance.SettingsModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.CameraController>((instance, di) =>
            {
                instance.CameraProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.CameraController>(instance =>
            {
                instance.CameraProvider = null;
                instance.GameStateModel = null;
                instance.SignalBus = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.CameraControllerMediator>((instance, di) =>
            {
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.CameraControllerMediator>(instance =>
            {
                instance.GameStateModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.CrisisAdService>((instance, di) =>
            {
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.CrisisAdService>(instance =>
            {
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.LevelModel = null;
                instance.Config = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.DailyCrisisService>((instance, di) =>
            {
                instance.DailyCrisisModel = di.Resolve<PixelFlow.Models.IDailyCrisisModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.DailyCrisisService>(instance =>
            {
                instance.DailyCrisisModel = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.GameplayTimerService>((instance, di) =>
            {
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.GameplayTimerService>(instance =>
            {
                instance.GameStateModel = null;
                instance.SignalBus = null;
                instance.LoggerService = null;
                instance.Config = null;
                instance.TickService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.HintService>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.HintService>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.LevelLoaderService>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.TutorialDriver = di.Resolve<PixelFlow.Services.ITutorialDriver>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.EconomyConfig = di.Resolve<PixelFlow.Data.EconomyConfigAsset>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.LevelLoaderService>(instance =>
            {
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameSessionModel = null;
                instance.HintModel = null;
                instance.HistoryService = null;
                instance.ObstacleService = null;
                instance.TutorialDriver = null;
                instance.SignalBus = null;
                instance.GameStateModel = null;
                instance.SaveThrottler = null;
                instance.PlayerPrefsService = null;
                instance.LoggerService = null;
                instance.EconomyConfig = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.ObstacleService>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.ObstacleService>(instance =>
            {
                instance.GridModel = null;
                instance.SignalBus = null;
                instance.Config = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.PathService>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.PowerUpService = di.Resolve<PixelFlow.Services.IPowerUpService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.PathService>(instance =>
            {
                instance.GridModel = null;
                instance.GameSessionModel = null;
                instance.PowerUpService = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.PowerUpService>((instance, di) =>
            {
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.PowerUpService>(instance =>
            {
                instance.Config = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.TutorialDriver>((instance, di) =>
            {
                instance.TutorialModel = di.Resolve<PixelFlow.Models.ITutorialModel>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.TutorialDriver>(instance =>
            {
                instance.TutorialModel = null;
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.VehicleSimulator>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.AudioService = di.Resolve<PixelFlow.Services.IAudioService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.CamProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
                instance.CrisisAdService = di.Resolve<PixelFlow.Services.ICrisisAdService>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
                instance.InventoryModel = di.Resolve<PixelFlow.Models.IInventoryModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.VehicleSimulator>(instance =>
            {
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.HintModel = null;
                instance.HapticService = null;
                instance.AudioService = null;
                instance.ObstacleService = null;
                instance.SettingsModel = null;
                instance.LoggerService = null;
                instance.CamProvider = null;
                instance.CrisisAdService = null;
                instance.Config = null;
                instance.TickService = null;
                instance.InventoryModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.GlobalRelease.InAppReviewService>((instance, di) =>
            {
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.Prefs = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.GlobalRelease.InAppReviewService>(instance =>
            {
                instance.SignalBus = null;
                instance.Prefs = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Models.InventoryModel>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Models.InventoryModel>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.ChangeThemeCommand>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.ChangeThemeCommand>(instance =>
            {
                instance.SettingsModel = null;
                instance.SignalBus = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.CheckWinConditionCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.EconomyConfig = di.Resolve<PixelFlow.Data.EconomyConfigAsset>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.CheckWinConditionCommand>(instance =>
            {
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.HintModel = null;
                instance.SignalBus = null;
                instance.LoggerService = null;
                instance.EconomyConfig = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.ClearJamCommand>((instance, di) =>
            {
                instance.PowerUpService = di.Resolve<PixelFlow.Services.IPowerUpService>();
                instance.PathService = di.Resolve<PixelFlow.Services.IPathService>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.AudioService = di.Resolve<PixelFlow.Services.IAudioService>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.ClearJamCommand>(instance =>
            {
                instance.PowerUpService = null;
                instance.PathService = null;
                instance.GameStateModel = null;
                instance.HistoryService = null;
                instance.AudioService = null;
                instance.SignalBus = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.InterstitialAdCommand>((instance, di) =>
            {
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.InterstitialAdCommand>(instance =>
            {
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.LevelVictoryCompositeHandler>((instance, di) =>
            {
                instance.FeedbackService = di.Resolve<Nexus.Core.Services.IFeedbackService>();
                instance.Logger = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.LevelVictoryCompositeHandler>(instance =>
            {
                instance.FeedbackService = null;
                instance.Logger = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.LoadLevelCommand>((instance, di) =>
            {
                instance.LevelLoaderService = di.Resolve<PixelFlow.Services.ILevelLoaderService>();
                instance.PowerUpService = di.Resolve<PixelFlow.Services.IPowerUpService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.LoadLevelCommand>(instance =>
            {
                instance.LevelLoaderService = null;
                instance.PowerUpService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.PauseSimulationCommand>((instance, di) =>
            {
                instance.VehicleSimulator = di.Resolve<PixelFlow.Services.IVehicleSimulator>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.PauseSimulationCommand>(instance =>
            {
                instance.VehicleSimulator = null;
                instance.GameStateModel = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.PlaceViaductCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.PlaceViaductCommand>(instance =>
            {
                instance.GridModel = null;
                instance.GameSessionModel = null;
                instance.GameStateModel = null;
                instance.SignalBus = null;
                instance.HistoryService = null;
                instance.SaveThrottler = null;
                instance.LevelModel = null;
                instance.HapticService = null;
                instance.LoggerService = null;
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.ProcessInputCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.SoundModel = di.Resolve<PixelFlow.Models.ISoundModel>();
                instance.PathService = di.Resolve<PixelFlow.Services.IPathService>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.ProcessInputCommand>(instance =>
            {
                instance.GridModel = null;
                instance.SignalBus = null;
                instance.SoundModel = null;
                instance.PathService = null;
                instance.GameStateModel = null;
                instance.HistoryService = null;
                instance.GameSessionModel = null;
                instance.LevelModel = null;
                instance.SaveThrottler = null;
                instance.HapticService = null;
                instance.ObstacleService = null;
                instance.PlayerPrefsService = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.RainbowRoadCommand>((instance, di) =>
            {
                instance.PowerUpService = di.Resolve<PixelFlow.Services.IPowerUpService>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.AudioService = di.Resolve<PixelFlow.Services.IAudioService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.RainbowRoadCommand>(instance =>
            {
                instance.PowerUpService = null;
                instance.GameStateModel = null;
                instance.AudioService = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.RedoCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.RedoCommand>(instance =>
            {
                instance.GridModel = null;
                instance.HistoryService = null;
                instance.SignalBus = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.SaveProgressCommand>((instance, di) =>
            {
                instance.ProgressModel = di.Resolve<PixelFlow.Models.IProgressModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.EconomyService = di.Resolve<Nexus.Core.Services.IEconomyService>();
                instance.Config = di.Resolve<PixelFlow.Data.GameConfig>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.SaveProgressCommand>(instance =>
            {
                instance.ProgressModel = null;
                instance.LevelModel = null;
                instance.SignalBus = null;
                instance.PlayerPrefsService = null;
                instance.LoggerService = null;
                instance.HintModel = null;
                instance.GameSessionModel = null;
                instance.EconomyService = null;
                instance.Config = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.StartSimulationCommand>((instance, di) =>
            {
                instance.VehicleSimulator = di.Resolve<PixelFlow.Services.IVehicleSimulator>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.StartSimulationCommand>(instance =>
            {
                instance.VehicleSimulator = null;
                instance.GameStateModel = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.UndoCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.CrisisAdService = di.Resolve<PixelFlow.Services.ICrisisAdService>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.UndoCommand>(instance =>
            {
                instance.GridModel = null;
                instance.HistoryService = null;
                instance.SignalBus = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.LevelModel = null;
                instance.SaveThrottler = null;
                instance.CrisisAdService = null;
                instance.HapticService = null;
                instance.PlayerPrefsService = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.UseHintCommand>((instance, di) =>
            {
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.PathService = di.Resolve<PixelFlow.Services.IPathService>();
                instance.HintService = di.Resolve<PixelFlow.Services.IHintService>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.UseHintCommand>(instance =>
            {
                instance.HintModel = null;
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.PathService = null;
                instance.HintService = null;
                instance.HistoryService = null;
                instance.SaveThrottler = null;
                instance.HapticService = null;
                instance.LoggerService = null;
                instance.PlayerPrefsService = null;
            });
        }

        // Forces IL2CPP to preserve members that are injected
        public static void PreserveMembers()
        {
            #pragma warning disable 0162, 0169, 0414, 0219
            if (false)
            {
                var _p_AudioService_PlayerPrefsService = default(Nexus.Core.Services.AudioService).PlayerPrefsService;
                _ = _p_AudioService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_AudioService_AudioRootProvider = default(Nexus.Core.Services.AudioService).AudioRootProvider;
                _ = _p_AudioService_AudioRootProvider; // Suppress CS0219 warning
                var _p_EconomyService_PlayerPrefsService = default(Nexus.Core.Services.EconomyService).PlayerPrefsService;
                _ = _p_EconomyService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_EconomyService_NetworkValidator = default(Nexus.Core.Services.EconomyService).NetworkValidator;
                _ = _p_EconomyService_NetworkValidator; // Suppress CS0219 warning
                var _p_FeedbackService_AudioService = default(Nexus.Core.Services.FeedbackService).AudioService;
                _ = _p_FeedbackService_AudioService; // Suppress CS0219 warning
                var _p_FeedbackService_HapticService = default(Nexus.Core.Services.FeedbackService).HapticService;
                _ = _p_FeedbackService_HapticService; // Suppress CS0219 warning
                var _p_HapticService_PlayerPrefsService = default(Nexus.Core.Services.HapticService).PlayerPrefsService;
                _ = _p_HapticService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_LocalizationService_PlayerPrefsService = default(Nexus.Core.Services.LocalizationService).PlayerPrefsService;
                _ = _p_LocalizationService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_LocalizationService_TableProvider = default(Nexus.Core.Services.LocalizationService).TableProvider;
                _ = _p_LocalizationService_TableProvider; // Suppress CS0219 warning
                var _p_ProgressionService_PlayerPrefsService = default(Nexus.Core.Services.ProgressionService).PlayerPrefsService;
                _ = _p_ProgressionService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_SaveThrottler_TickService = default(Nexus.Core.Services.SaveThrottler).TickService;
                _ = _p_SaveThrottler_TickService; // Suppress CS0219 warning
                var _p_SaveThrottler_TimeProvider = default(Nexus.Core.Services.SaveThrottler).TimeProvider;
                _ = _p_SaveThrottler_TimeProvider; // Suppress CS0219 warning
                var _p_WindowManager_AssetProvider = default(Nexus.Core.Services.WindowManager).AssetProvider;
                _ = _p_WindowManager_AssetProvider; // Suppress CS0219 warning
                var _p_CellView_ThemePalette = default(PixelFlow.Views.CellView).ThemePalette;
                _ = _p_CellView_ThemePalette; // Suppress CS0219 warning
                var _p_CellView_ObstacleService = default(PixelFlow.Views.CellView).ObstacleService;
                _ = _p_CellView_ObstacleService; // Suppress CS0219 warning
                var _p_DailyCrisisMediator_DailyCrisisModel = default(PixelFlow.Views.DailyCrisisMediator).DailyCrisisModel;
                _ = _p_DailyCrisisMediator_DailyCrisisModel; // Suppress CS0219 warning
                var _p_DailyCrisisMediator_DailyCrisisService = default(PixelFlow.Views.DailyCrisisMediator).DailyCrisisService;
                _ = _p_DailyCrisisMediator_DailyCrisisService; // Suppress CS0219 warning
                var _p_DailyCrisisMediator_LoggerService = default(PixelFlow.Views.DailyCrisisMediator).LoggerService;
                _ = _p_DailyCrisisMediator_LoggerService; // Suppress CS0219 warning
                var _p_GarageMediator_InventoryModel = default(PixelFlow.Views.GarageMediator).InventoryModel;
                _ = _p_GarageMediator_InventoryModel; // Suppress CS0219 warning
                var _p_GarageMediator_LoggerService = default(PixelFlow.Views.GarageMediator).LoggerService;
                _ = _p_GarageMediator_LoggerService; // Suppress CS0219 warning
                var _p_GarageView_LoggerService = default(PixelFlow.Views.GarageView).LoggerService;
                _ = _p_GarageView_LoggerService; // Suppress CS0219 warning
                var _p_GridMediator_GridModel = default(PixelFlow.Views.GridMediator).GridModel;
                _ = _p_GridMediator_GridModel; // Suppress CS0219 warning
                var _p_GridMediator_SettingsModel = default(PixelFlow.Views.GridMediator).SettingsModel;
                _ = _p_GridMediator_SettingsModel; // Suppress CS0219 warning
                var _p_GridMediator_Logger = default(PixelFlow.Views.GridMediator).Logger;
                _ = _p_GridMediator_Logger; // Suppress CS0219 warning
                var _p_GridMediator_AudioService = default(PixelFlow.Views.GridMediator).AudioService;
                _ = _p_GridMediator_AudioService; // Suppress CS0219 warning
                var _p_GridView_CameraProvider = default(PixelFlow.Views.GridView).CameraProvider;
                _ = _p_GridView_CameraProvider; // Suppress CS0219 warning
                var _p_GridView_LoggerService = default(PixelFlow.Views.GridView).LoggerService;
                _ = _p_GridView_LoggerService; // Suppress CS0219 warning
                var _p_GridView_Config = default(PixelFlow.Views.GridView).Config;
                _ = _p_GridView_Config; // Suppress CS0219 warning
                var _p_GridView_TickService = default(PixelFlow.Views.GridView).TickService;
                _ = _p_GridView_TickService; // Suppress CS0219 warning
                var _p_HUDMediator_LoggerService = default(PixelFlow.Views.HUDMediator).LoggerService;
                _ = _p_HUDMediator_LoggerService; // Suppress CS0219 warning
                var _p_HUDMediator_HintModel = default(PixelFlow.Views.HUDMediator).HintModel;
                _ = _p_HUDMediator_HintModel; // Suppress CS0219 warning
                var _p_HUDMediator_LevelModel = default(PixelFlow.Views.HUDMediator).LevelModel;
                _ = _p_HUDMediator_LevelModel; // Suppress CS0219 warning
                var _p_HUDMediator_SettingsModel = default(PixelFlow.Views.HUDMediator).SettingsModel;
                _ = _p_HUDMediator_SettingsModel; // Suppress CS0219 warning
                var _p_HUDMediator_GameStateModel = default(PixelFlow.Views.HUDMediator).GameStateModel;
                _ = _p_HUDMediator_GameStateModel; // Suppress CS0219 warning
                var _p_HUDMediator_GameSessionModel = default(PixelFlow.Views.HUDMediator).GameSessionModel;
                _ = _p_HUDMediator_GameSessionModel; // Suppress CS0219 warning
                var _p_HUDMediator_HistoryService = default(PixelFlow.Views.HUDMediator).HistoryService;
                _ = _p_HUDMediator_HistoryService; // Suppress CS0219 warning
                var _p_HUDMediator_ProgressionService = default(PixelFlow.Views.HUDMediator).ProgressionService;
                _ = _p_HUDMediator_ProgressionService; // Suppress CS0219 warning
                var _p_HUDMediator_LocalizationService = default(PixelFlow.Views.HUDMediator).LocalizationService;
                _ = _p_HUDMediator_LocalizationService; // Suppress CS0219 warning
                var _p_HUDMediator_PowerUpService = default(PixelFlow.Views.HUDMediator).PowerUpService;
                _ = _p_HUDMediator_PowerUpService; // Suppress CS0219 warning
                var _p_HUDView_LoggerService = default(PixelFlow.Views.HUDView).LoggerService;
                _ = _p_HUDView_LoggerService; // Suppress CS0219 warning
                var _p_HUDView_TickService = default(PixelFlow.Views.HUDView).TickService;
                _ = _p_HUDView_TickService; // Suppress CS0219 warning
                var _p_MainMenuMediator_GameStateModel = default(PixelFlow.Views.MainMenuMediator).GameStateModel;
                _ = _p_MainMenuMediator_GameStateModel; // Suppress CS0219 warning
                var _p_MainMenuMediator_ProgressModel = default(PixelFlow.Views.MainMenuMediator).ProgressModel;
                _ = _p_MainMenuMediator_ProgressModel; // Suppress CS0219 warning
                var _p_MainMenuMediator_InventoryModel = default(PixelFlow.Views.MainMenuMediator).InventoryModel;
                _ = _p_MainMenuMediator_InventoryModel; // Suppress CS0219 warning
                var _p_MainMenuMediator_ProgressionService = default(PixelFlow.Views.MainMenuMediator).ProgressionService;
                _ = _p_MainMenuMediator_ProgressionService; // Suppress CS0219 warning
                var _p_MainMenuMediator_LoggerService = default(PixelFlow.Views.MainMenuMediator).LoggerService;
                _ = _p_MainMenuMediator_LoggerService; // Suppress CS0219 warning
                var _p_MainMenuMediator_GridModel = default(PixelFlow.Views.MainMenuMediator).GridModel;
                _ = _p_MainMenuMediator_GridModel; // Suppress CS0219 warning
                var _p_MainMenuMediator_GameSessionModel = default(PixelFlow.Views.MainMenuMediator).GameSessionModel;
                _ = _p_MainMenuMediator_GameSessionModel; // Suppress CS0219 warning
                var _p_MainMenuMediator_LevelModel = default(PixelFlow.Views.MainMenuMediator).LevelModel;
                _ = _p_MainMenuMediator_LevelModel; // Suppress CS0219 warning
                var _p_MainMenuMediator_PlayerPrefsService = default(PixelFlow.Views.MainMenuMediator).PlayerPrefsService;
                _ = _p_MainMenuMediator_PlayerPrefsService; // Suppress CS0219 warning
                var _p_MainMenuMediator_ObstacleService = default(PixelFlow.Views.MainMenuMediator).ObstacleService;
                _ = _p_MainMenuMediator_ObstacleService; // Suppress CS0219 warning
                var _p_MainMenuMediator_TutorialDriver = default(PixelFlow.Views.MainMenuMediator).TutorialDriver;
                _ = _p_MainMenuMediator_TutorialDriver; // Suppress CS0219 warning
                var _p_MainMenuMediator_SignalBus = default(PixelFlow.Views.MainMenuMediator).SignalBus;
                _ = _p_MainMenuMediator_SignalBus; // Suppress CS0219 warning
                var _p_MainMenuView_LoggerService = default(PixelFlow.Views.MainMenuView).LoggerService;
                _ = _p_MainMenuView_LoggerService; // Suppress CS0219 warning
                var _p_SettingsMediator_SettingsModel = default(PixelFlow.Views.SettingsMediator).SettingsModel;
                _ = _p_SettingsMediator_SettingsModel; // Suppress CS0219 warning
                var _p_SettingsMediator_GameStateModel = default(PixelFlow.Views.SettingsMediator).GameStateModel;
                _ = _p_SettingsMediator_GameStateModel; // Suppress CS0219 warning
                var _p_SettingsMediator_LoggerService = default(PixelFlow.Views.SettingsMediator).LoggerService;
                _ = _p_SettingsMediator_LoggerService; // Suppress CS0219 warning
                var _p_SettingsView_LoggerService = default(PixelFlow.Views.SettingsView).LoggerService;
                _ = _p_SettingsView_LoggerService; // Suppress CS0219 warning
                var _p_SoundHandlerMediator_SoundModel = default(PixelFlow.Views.SoundHandlerMediator).SoundModel;
                _ = _p_SoundHandlerMediator_SoundModel; // Suppress CS0219 warning
                var _p_SplashMediator_LoggerService = default(PixelFlow.Views.SplashMediator).LoggerService;
                _ = _p_SplashMediator_LoggerService; // Suppress CS0219 warning
                var _p_SplashView_LoggerService = default(PixelFlow.Views.SplashView).LoggerService;
                _ = _p_SplashView_LoggerService; // Suppress CS0219 warning
                var _p_ThemeHandlerMediator_SettingsModel = default(PixelFlow.Views.ThemeHandlerMediator).SettingsModel;
                _ = _p_ThemeHandlerMediator_SettingsModel; // Suppress CS0219 warning
                var _p_ThemeHandlerMediator_CameraProvider = default(PixelFlow.Views.ThemeHandlerMediator).CameraProvider;
                _ = _p_ThemeHandlerMediator_CameraProvider; // Suppress CS0219 warning
                var _p_ThemeHandlerMediator_LoggerService = default(PixelFlow.Views.ThemeHandlerMediator).LoggerService;
                _ = _p_ThemeHandlerMediator_LoggerService; // Suppress CS0219 warning
                var _p_ThemeHandlerMediator_ThemePalette = default(PixelFlow.Views.ThemeHandlerMediator).ThemePalette;
                _ = _p_ThemeHandlerMediator_ThemePalette; // Suppress CS0219 warning
                var _p_TutorialView_TickService = default(PixelFlow.Views.TutorialView).TickService;
                _ = _p_TutorialView_TickService; // Suppress CS0219 warning
                var _p_TutorialMediator_TutorialModel = default(PixelFlow.Views.TutorialMediator).TutorialModel;
                _ = _p_TutorialMediator_TutorialModel; // Suppress CS0219 warning
                var _p_TutorialMediator_TutorialDriver = default(PixelFlow.Views.TutorialMediator).TutorialDriver;
                _ = _p_TutorialMediator_TutorialDriver; // Suppress CS0219 warning
                var _p_AdManagerService_InventoryModel = default(PixelFlow.Services.AdManagerService).InventoryModel;
                _ = _p_AdManagerService_InventoryModel; // Suppress CS0219 warning
                var _p_AdManagerService_LoggerService = default(PixelFlow.Services.AdManagerService).LoggerService;
                _ = _p_AdManagerService_LoggerService; // Suppress CS0219 warning
                var _p_AdManagerService_GameSessionModel = default(PixelFlow.Services.AdManagerService).GameSessionModel;
                _ = _p_AdManagerService_GameSessionModel; // Suppress CS0219 warning
                var _p_AdManagerService_SignalBus = default(PixelFlow.Services.AdManagerService).SignalBus;
                _ = _p_AdManagerService_SignalBus; // Suppress CS0219 warning
                var _p_AdManagerService_LevelModel = default(PixelFlow.Services.AdManagerService).LevelModel;
                _ = _p_AdManagerService_LevelModel; // Suppress CS0219 warning
                var _p_AdManagerService_Config = default(PixelFlow.Services.AdManagerService).Config;
                _ = _p_AdManagerService_Config; // Suppress CS0219 warning
                var _p_AudioService_SettingsModel = default(PixelFlow.Services.AudioService).SettingsModel;
                _ = _p_AudioService_SettingsModel; // Suppress CS0219 warning
                var _p_CameraController_CameraProvider = default(PixelFlow.Services.CameraController).CameraProvider;
                _ = _p_CameraController_CameraProvider; // Suppress CS0219 warning
                var _p_CameraController_GameStateModel = default(PixelFlow.Services.CameraController).GameStateModel;
                _ = _p_CameraController_GameStateModel; // Suppress CS0219 warning
                var _p_CameraController_SignalBus = default(PixelFlow.Services.CameraController).SignalBus;
                _ = _p_CameraController_SignalBus; // Suppress CS0219 warning
                var _p_CameraControllerMediator_GameStateModel = default(PixelFlow.Services.CameraControllerMediator).GameStateModel;
                _ = _p_CameraControllerMediator_GameStateModel; // Suppress CS0219 warning
                var _p_CrisisAdService_GameSessionModel = default(PixelFlow.Services.CrisisAdService).GameSessionModel;
                _ = _p_CrisisAdService_GameSessionModel; // Suppress CS0219 warning
                var _p_CrisisAdService_SignalBus = default(PixelFlow.Services.CrisisAdService).SignalBus;
                _ = _p_CrisisAdService_SignalBus; // Suppress CS0219 warning
                var _p_CrisisAdService_LevelModel = default(PixelFlow.Services.CrisisAdService).LevelModel;
                _ = _p_CrisisAdService_LevelModel; // Suppress CS0219 warning
                var _p_CrisisAdService_Config = default(PixelFlow.Services.CrisisAdService).Config;
                _ = _p_CrisisAdService_Config; // Suppress CS0219 warning
                var _p_DailyCrisisService_DailyCrisisModel = default(PixelFlow.Services.DailyCrisisService).DailyCrisisModel;
                _ = _p_DailyCrisisService_DailyCrisisModel; // Suppress CS0219 warning
                var _p_DailyCrisisService_LoggerService = default(PixelFlow.Services.DailyCrisisService).LoggerService;
                _ = _p_DailyCrisisService_LoggerService; // Suppress CS0219 warning
                var _p_GameplayTimerService_GameStateModel = default(PixelFlow.Services.GameplayTimerService).GameStateModel;
                _ = _p_GameplayTimerService_GameStateModel; // Suppress CS0219 warning
                var _p_GameplayTimerService_SignalBus = default(PixelFlow.Services.GameplayTimerService).SignalBus;
                _ = _p_GameplayTimerService_SignalBus; // Suppress CS0219 warning
                var _p_GameplayTimerService_LoggerService = default(PixelFlow.Services.GameplayTimerService).LoggerService;
                _ = _p_GameplayTimerService_LoggerService; // Suppress CS0219 warning
                var _p_GameplayTimerService_Config = default(PixelFlow.Services.GameplayTimerService).Config;
                _ = _p_GameplayTimerService_Config; // Suppress CS0219 warning
                var _p_GameplayTimerService_TickService = default(PixelFlow.Services.GameplayTimerService).TickService;
                _ = _p_GameplayTimerService_TickService; // Suppress CS0219 warning
                var _p_HintService_LoggerService = default(PixelFlow.Services.HintService).LoggerService;
                _ = _p_HintService_LoggerService; // Suppress CS0219 warning
                var _p_LevelLoaderService_GridModel = default(PixelFlow.Services.LevelLoaderService).GridModel;
                _ = _p_LevelLoaderService_GridModel; // Suppress CS0219 warning
                var _p_LevelLoaderService_LevelModel = default(PixelFlow.Services.LevelLoaderService).LevelModel;
                _ = _p_LevelLoaderService_LevelModel; // Suppress CS0219 warning
                var _p_LevelLoaderService_GameSessionModel = default(PixelFlow.Services.LevelLoaderService).GameSessionModel;
                _ = _p_LevelLoaderService_GameSessionModel; // Suppress CS0219 warning
                var _p_LevelLoaderService_HintModel = default(PixelFlow.Services.LevelLoaderService).HintModel;
                _ = _p_LevelLoaderService_HintModel; // Suppress CS0219 warning
                var _p_LevelLoaderService_HistoryService = default(PixelFlow.Services.LevelLoaderService).HistoryService;
                _ = _p_LevelLoaderService_HistoryService; // Suppress CS0219 warning
                var _p_LevelLoaderService_ObstacleService = default(PixelFlow.Services.LevelLoaderService).ObstacleService;
                _ = _p_LevelLoaderService_ObstacleService; // Suppress CS0219 warning
                var _p_LevelLoaderService_TutorialDriver = default(PixelFlow.Services.LevelLoaderService).TutorialDriver;
                _ = _p_LevelLoaderService_TutorialDriver; // Suppress CS0219 warning
                var _p_LevelLoaderService_SignalBus = default(PixelFlow.Services.LevelLoaderService).SignalBus;
                _ = _p_LevelLoaderService_SignalBus; // Suppress CS0219 warning
                var _p_LevelLoaderService_GameStateModel = default(PixelFlow.Services.LevelLoaderService).GameStateModel;
                _ = _p_LevelLoaderService_GameStateModel; // Suppress CS0219 warning
                var _p_LevelLoaderService_SaveThrottler = default(PixelFlow.Services.LevelLoaderService).SaveThrottler;
                _ = _p_LevelLoaderService_SaveThrottler; // Suppress CS0219 warning
                var _p_LevelLoaderService_PlayerPrefsService = default(PixelFlow.Services.LevelLoaderService).PlayerPrefsService;
                _ = _p_LevelLoaderService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_LevelLoaderService_LoggerService = default(PixelFlow.Services.LevelLoaderService).LoggerService;
                _ = _p_LevelLoaderService_LoggerService; // Suppress CS0219 warning
                var _p_LevelLoaderService_EconomyConfig = default(PixelFlow.Services.LevelLoaderService).EconomyConfig;
                _ = _p_LevelLoaderService_EconomyConfig; // Suppress CS0219 warning
                var _p_ObstacleService_GridModel = default(PixelFlow.Services.ObstacleService).GridModel;
                _ = _p_ObstacleService_GridModel; // Suppress CS0219 warning
                var _p_ObstacleService_SignalBus = default(PixelFlow.Services.ObstacleService).SignalBus;
                _ = _p_ObstacleService_SignalBus; // Suppress CS0219 warning
                var _p_ObstacleService_Config = default(PixelFlow.Services.ObstacleService).Config;
                _ = _p_ObstacleService_Config; // Suppress CS0219 warning
                var _p_ObstacleService_LoggerService = default(PixelFlow.Services.ObstacleService).LoggerService;
                _ = _p_ObstacleService_LoggerService; // Suppress CS0219 warning
                var _p_PathService_GridModel = default(PixelFlow.Services.PathService).GridModel;
                _ = _p_PathService_GridModel; // Suppress CS0219 warning
                var _p_PathService_GameSessionModel = default(PixelFlow.Services.PathService).GameSessionModel;
                _ = _p_PathService_GameSessionModel; // Suppress CS0219 warning
                var _p_PathService_PowerUpService = default(PixelFlow.Services.PathService).PowerUpService;
                _ = _p_PathService_PowerUpService; // Suppress CS0219 warning
                var _p_PathService_LoggerService = default(PixelFlow.Services.PathService).LoggerService;
                _ = _p_PathService_LoggerService; // Suppress CS0219 warning
                var _p_PowerUpService_Config = default(PixelFlow.Services.PowerUpService).Config;
                _ = _p_PowerUpService_Config; // Suppress CS0219 warning
                var _p_TutorialDriver_TutorialModel = default(PixelFlow.Services.TutorialDriver).TutorialModel;
                _ = _p_TutorialDriver_TutorialModel; // Suppress CS0219 warning
                var _p_TutorialDriver_PlayerPrefsService = default(PixelFlow.Services.TutorialDriver).PlayerPrefsService;
                _ = _p_TutorialDriver_PlayerPrefsService; // Suppress CS0219 warning
                var _p_VehicleSimulator_GridModel = default(PixelFlow.Services.VehicleSimulator).GridModel;
                _ = _p_VehicleSimulator_GridModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_LevelModel = default(PixelFlow.Services.VehicleSimulator).LevelModel;
                _ = _p_VehicleSimulator_LevelModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_GameStateModel = default(PixelFlow.Services.VehicleSimulator).GameStateModel;
                _ = _p_VehicleSimulator_GameStateModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_GameSessionModel = default(PixelFlow.Services.VehicleSimulator).GameSessionModel;
                _ = _p_VehicleSimulator_GameSessionModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_SignalBus = default(PixelFlow.Services.VehicleSimulator).SignalBus;
                _ = _p_VehicleSimulator_SignalBus; // Suppress CS0219 warning
                var _p_VehicleSimulator_HintModel = default(PixelFlow.Services.VehicleSimulator).HintModel;
                _ = _p_VehicleSimulator_HintModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_HapticService = default(PixelFlow.Services.VehicleSimulator).HapticService;
                _ = _p_VehicleSimulator_HapticService; // Suppress CS0219 warning
                var _p_VehicleSimulator_AudioService = default(PixelFlow.Services.VehicleSimulator).AudioService;
                _ = _p_VehicleSimulator_AudioService; // Suppress CS0219 warning
                var _p_VehicleSimulator_ObstacleService = default(PixelFlow.Services.VehicleSimulator).ObstacleService;
                _ = _p_VehicleSimulator_ObstacleService; // Suppress CS0219 warning
                var _p_VehicleSimulator_SettingsModel = default(PixelFlow.Services.VehicleSimulator).SettingsModel;
                _ = _p_VehicleSimulator_SettingsModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_LoggerService = default(PixelFlow.Services.VehicleSimulator).LoggerService;
                _ = _p_VehicleSimulator_LoggerService; // Suppress CS0219 warning
                var _p_VehicleSimulator_CamProvider = default(PixelFlow.Services.VehicleSimulator).CamProvider;
                _ = _p_VehicleSimulator_CamProvider; // Suppress CS0219 warning
                var _p_VehicleSimulator_CrisisAdService = default(PixelFlow.Services.VehicleSimulator).CrisisAdService;
                _ = _p_VehicleSimulator_CrisisAdService; // Suppress CS0219 warning
                var _p_VehicleSimulator_Config = default(PixelFlow.Services.VehicleSimulator).Config;
                _ = _p_VehicleSimulator_Config; // Suppress CS0219 warning
                var _p_VehicleSimulator_TickService = default(PixelFlow.Services.VehicleSimulator).TickService;
                _ = _p_VehicleSimulator_TickService; // Suppress CS0219 warning
                var _p_VehicleSimulator_InventoryModel = default(PixelFlow.Services.VehicleSimulator).InventoryModel;
                _ = _p_VehicleSimulator_InventoryModel; // Suppress CS0219 warning
                var _p_InAppReviewService_SignalBus = default(PixelFlow.Services.GlobalRelease.InAppReviewService).SignalBus;
                _ = _p_InAppReviewService_SignalBus; // Suppress CS0219 warning
                var _p_InAppReviewService_Prefs = default(PixelFlow.Services.GlobalRelease.InAppReviewService).Prefs;
                _ = _p_InAppReviewService_Prefs; // Suppress CS0219 warning
                var _p_InventoryModel_LoggerService = default(PixelFlow.Models.InventoryModel).LoggerService;
                _ = _p_InventoryModel_LoggerService; // Suppress CS0219 warning
                var _p_ChangeThemeCommand_SettingsModel = default(PixelFlow.Commands.ChangeThemeCommand).SettingsModel;
                _ = _p_ChangeThemeCommand_SettingsModel; // Suppress CS0219 warning
                var _p_ChangeThemeCommand_SignalBus = default(PixelFlow.Commands.ChangeThemeCommand).SignalBus;
                _ = _p_ChangeThemeCommand_SignalBus; // Suppress CS0219 warning
                var _p_ChangeThemeCommand_LoggerService = default(PixelFlow.Commands.ChangeThemeCommand).LoggerService;
                _ = _p_ChangeThemeCommand_LoggerService; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_GridModel = default(PixelFlow.Commands.CheckWinConditionCommand).GridModel;
                _ = _p_CheckWinConditionCommand_GridModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_LevelModel = default(PixelFlow.Commands.CheckWinConditionCommand).LevelModel;
                _ = _p_CheckWinConditionCommand_LevelModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_GameStateModel = default(PixelFlow.Commands.CheckWinConditionCommand).GameStateModel;
                _ = _p_CheckWinConditionCommand_GameStateModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_GameSessionModel = default(PixelFlow.Commands.CheckWinConditionCommand).GameSessionModel;
                _ = _p_CheckWinConditionCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_HintModel = default(PixelFlow.Commands.CheckWinConditionCommand).HintModel;
                _ = _p_CheckWinConditionCommand_HintModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_SignalBus = default(PixelFlow.Commands.CheckWinConditionCommand).SignalBus;
                _ = _p_CheckWinConditionCommand_SignalBus; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_LoggerService = default(PixelFlow.Commands.CheckWinConditionCommand).LoggerService;
                _ = _p_CheckWinConditionCommand_LoggerService; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_EconomyConfig = default(PixelFlow.Commands.CheckWinConditionCommand).EconomyConfig;
                _ = _p_CheckWinConditionCommand_EconomyConfig; // Suppress CS0219 warning
                var _p_ClearJamCommand_PowerUpService = default(PixelFlow.Commands.ClearJamCommand).PowerUpService;
                _ = _p_ClearJamCommand_PowerUpService; // Suppress CS0219 warning
                var _p_ClearJamCommand_PathService = default(PixelFlow.Commands.ClearJamCommand).PathService;
                _ = _p_ClearJamCommand_PathService; // Suppress CS0219 warning
                var _p_ClearJamCommand_GameStateModel = default(PixelFlow.Commands.ClearJamCommand).GameStateModel;
                _ = _p_ClearJamCommand_GameStateModel; // Suppress CS0219 warning
                var _p_ClearJamCommand_HistoryService = default(PixelFlow.Commands.ClearJamCommand).HistoryService;
                _ = _p_ClearJamCommand_HistoryService; // Suppress CS0219 warning
                var _p_ClearJamCommand_AudioService = default(PixelFlow.Commands.ClearJamCommand).AudioService;
                _ = _p_ClearJamCommand_AudioService; // Suppress CS0219 warning
                var _p_ClearJamCommand_SignalBus = default(PixelFlow.Commands.ClearJamCommand).SignalBus;
                _ = _p_ClearJamCommand_SignalBus; // Suppress CS0219 warning
                var _p_ClearJamCommand_LoggerService = default(PixelFlow.Commands.ClearJamCommand).LoggerService;
                _ = _p_ClearJamCommand_LoggerService; // Suppress CS0219 warning
                var _p_InterstitialAdCommand_LoggerService = default(PixelFlow.Commands.InterstitialAdCommand).LoggerService;
                _ = _p_InterstitialAdCommand_LoggerService; // Suppress CS0219 warning
                var _p_LevelVictoryCompositeHandler_FeedbackService = default(PixelFlow.Commands.LevelVictoryCompositeHandler).FeedbackService;
                _ = _p_LevelVictoryCompositeHandler_FeedbackService; // Suppress CS0219 warning
                var _p_LevelVictoryCompositeHandler_Logger = default(PixelFlow.Commands.LevelVictoryCompositeHandler).Logger;
                _ = _p_LevelVictoryCompositeHandler_Logger; // Suppress CS0219 warning
                var _p_LoadLevelCommand_LevelLoaderService = default(PixelFlow.Commands.LoadLevelCommand).LevelLoaderService;
                _ = _p_LoadLevelCommand_LevelLoaderService; // Suppress CS0219 warning
                var _p_LoadLevelCommand_PowerUpService = default(PixelFlow.Commands.LoadLevelCommand).PowerUpService;
                _ = _p_LoadLevelCommand_PowerUpService; // Suppress CS0219 warning
                var _p_PauseSimulationCommand_VehicleSimulator = default(PixelFlow.Commands.PauseSimulationCommand).VehicleSimulator;
                _ = _p_PauseSimulationCommand_VehicleSimulator; // Suppress CS0219 warning
                var _p_PauseSimulationCommand_GameStateModel = default(PixelFlow.Commands.PauseSimulationCommand).GameStateModel;
                _ = _p_PauseSimulationCommand_GameStateModel; // Suppress CS0219 warning
                var _p_PauseSimulationCommand_LoggerService = default(PixelFlow.Commands.PauseSimulationCommand).LoggerService;
                _ = _p_PauseSimulationCommand_LoggerService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_GridModel = default(PixelFlow.Commands.PlaceViaductCommand).GridModel;
                _ = _p_PlaceViaductCommand_GridModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_GameSessionModel = default(PixelFlow.Commands.PlaceViaductCommand).GameSessionModel;
                _ = _p_PlaceViaductCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_GameStateModel = default(PixelFlow.Commands.PlaceViaductCommand).GameStateModel;
                _ = _p_PlaceViaductCommand_GameStateModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_SignalBus = default(PixelFlow.Commands.PlaceViaductCommand).SignalBus;
                _ = _p_PlaceViaductCommand_SignalBus; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_HistoryService = default(PixelFlow.Commands.PlaceViaductCommand).HistoryService;
                _ = _p_PlaceViaductCommand_HistoryService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_SaveThrottler = default(PixelFlow.Commands.PlaceViaductCommand).SaveThrottler;
                _ = _p_PlaceViaductCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_LevelModel = default(PixelFlow.Commands.PlaceViaductCommand).LevelModel;
                _ = _p_PlaceViaductCommand_LevelModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_HapticService = default(PixelFlow.Commands.PlaceViaductCommand).HapticService;
                _ = _p_PlaceViaductCommand_HapticService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_LoggerService = default(PixelFlow.Commands.PlaceViaductCommand).LoggerService;
                _ = _p_PlaceViaductCommand_LoggerService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_PlayerPrefsService = default(PixelFlow.Commands.PlaceViaductCommand).PlayerPrefsService;
                _ = _p_PlaceViaductCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_GridModel = default(PixelFlow.Commands.ProcessInputCommand).GridModel;
                _ = _p_ProcessInputCommand_GridModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_SignalBus = default(PixelFlow.Commands.ProcessInputCommand).SignalBus;
                _ = _p_ProcessInputCommand_SignalBus; // Suppress CS0219 warning
                var _p_ProcessInputCommand_SoundModel = default(PixelFlow.Commands.ProcessInputCommand).SoundModel;
                _ = _p_ProcessInputCommand_SoundModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_PathService = default(PixelFlow.Commands.ProcessInputCommand).PathService;
                _ = _p_ProcessInputCommand_PathService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_GameStateModel = default(PixelFlow.Commands.ProcessInputCommand).GameStateModel;
                _ = _p_ProcessInputCommand_GameStateModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_HistoryService = default(PixelFlow.Commands.ProcessInputCommand).HistoryService;
                _ = _p_ProcessInputCommand_HistoryService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_GameSessionModel = default(PixelFlow.Commands.ProcessInputCommand).GameSessionModel;
                _ = _p_ProcessInputCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_LevelModel = default(PixelFlow.Commands.ProcessInputCommand).LevelModel;
                _ = _p_ProcessInputCommand_LevelModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_SaveThrottler = default(PixelFlow.Commands.ProcessInputCommand).SaveThrottler;
                _ = _p_ProcessInputCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_ProcessInputCommand_HapticService = default(PixelFlow.Commands.ProcessInputCommand).HapticService;
                _ = _p_ProcessInputCommand_HapticService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_ObstacleService = default(PixelFlow.Commands.ProcessInputCommand).ObstacleService;
                _ = _p_ProcessInputCommand_ObstacleService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_PlayerPrefsService = default(PixelFlow.Commands.ProcessInputCommand).PlayerPrefsService;
                _ = _p_ProcessInputCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_LoggerService = default(PixelFlow.Commands.ProcessInputCommand).LoggerService;
                _ = _p_ProcessInputCommand_LoggerService; // Suppress CS0219 warning
                var _p_RainbowRoadCommand_PowerUpService = default(PixelFlow.Commands.RainbowRoadCommand).PowerUpService;
                _ = _p_RainbowRoadCommand_PowerUpService; // Suppress CS0219 warning
                var _p_RainbowRoadCommand_GameStateModel = default(PixelFlow.Commands.RainbowRoadCommand).GameStateModel;
                _ = _p_RainbowRoadCommand_GameStateModel; // Suppress CS0219 warning
                var _p_RainbowRoadCommand_AudioService = default(PixelFlow.Commands.RainbowRoadCommand).AudioService;
                _ = _p_RainbowRoadCommand_AudioService; // Suppress CS0219 warning
                var _p_RainbowRoadCommand_LoggerService = default(PixelFlow.Commands.RainbowRoadCommand).LoggerService;
                _ = _p_RainbowRoadCommand_LoggerService; // Suppress CS0219 warning
                var _p_RedoCommand_GridModel = default(PixelFlow.Commands.RedoCommand).GridModel;
                _ = _p_RedoCommand_GridModel; // Suppress CS0219 warning
                var _p_RedoCommand_HistoryService = default(PixelFlow.Commands.RedoCommand).HistoryService;
                _ = _p_RedoCommand_HistoryService; // Suppress CS0219 warning
                var _p_RedoCommand_SignalBus = default(PixelFlow.Commands.RedoCommand).SignalBus;
                _ = _p_RedoCommand_SignalBus; // Suppress CS0219 warning
                var _p_RedoCommand_GameStateModel = default(PixelFlow.Commands.RedoCommand).GameStateModel;
                _ = _p_RedoCommand_GameStateModel; // Suppress CS0219 warning
                var _p_RedoCommand_GameSessionModel = default(PixelFlow.Commands.RedoCommand).GameSessionModel;
                _ = _p_RedoCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_RedoCommand_LoggerService = default(PixelFlow.Commands.RedoCommand).LoggerService;
                _ = _p_RedoCommand_LoggerService; // Suppress CS0219 warning
                var _p_SaveProgressCommand_ProgressModel = default(PixelFlow.Commands.SaveProgressCommand).ProgressModel;
                _ = _p_SaveProgressCommand_ProgressModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_LevelModel = default(PixelFlow.Commands.SaveProgressCommand).LevelModel;
                _ = _p_SaveProgressCommand_LevelModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_SignalBus = default(PixelFlow.Commands.SaveProgressCommand).SignalBus;
                _ = _p_SaveProgressCommand_SignalBus; // Suppress CS0219 warning
                var _p_SaveProgressCommand_PlayerPrefsService = default(PixelFlow.Commands.SaveProgressCommand).PlayerPrefsService;
                _ = _p_SaveProgressCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_SaveProgressCommand_LoggerService = default(PixelFlow.Commands.SaveProgressCommand).LoggerService;
                _ = _p_SaveProgressCommand_LoggerService; // Suppress CS0219 warning
                var _p_SaveProgressCommand_HintModel = default(PixelFlow.Commands.SaveProgressCommand).HintModel;
                _ = _p_SaveProgressCommand_HintModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_GameSessionModel = default(PixelFlow.Commands.SaveProgressCommand).GameSessionModel;
                _ = _p_SaveProgressCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_EconomyService = default(PixelFlow.Commands.SaveProgressCommand).EconomyService;
                _ = _p_SaveProgressCommand_EconomyService; // Suppress CS0219 warning
                var _p_SaveProgressCommand_Config = default(PixelFlow.Commands.SaveProgressCommand).Config;
                _ = _p_SaveProgressCommand_Config; // Suppress CS0219 warning
                var _p_StartSimulationCommand_VehicleSimulator = default(PixelFlow.Commands.StartSimulationCommand).VehicleSimulator;
                _ = _p_StartSimulationCommand_VehicleSimulator; // Suppress CS0219 warning
                var _p_StartSimulationCommand_GameStateModel = default(PixelFlow.Commands.StartSimulationCommand).GameStateModel;
                _ = _p_StartSimulationCommand_GameStateModel; // Suppress CS0219 warning
                var _p_StartSimulationCommand_LoggerService = default(PixelFlow.Commands.StartSimulationCommand).LoggerService;
                _ = _p_StartSimulationCommand_LoggerService; // Suppress CS0219 warning
                var _p_UndoCommand_GridModel = default(PixelFlow.Commands.UndoCommand).GridModel;
                _ = _p_UndoCommand_GridModel; // Suppress CS0219 warning
                var _p_UndoCommand_HistoryService = default(PixelFlow.Commands.UndoCommand).HistoryService;
                _ = _p_UndoCommand_HistoryService; // Suppress CS0219 warning
                var _p_UndoCommand_SignalBus = default(PixelFlow.Commands.UndoCommand).SignalBus;
                _ = _p_UndoCommand_SignalBus; // Suppress CS0219 warning
                var _p_UndoCommand_GameStateModel = default(PixelFlow.Commands.UndoCommand).GameStateModel;
                _ = _p_UndoCommand_GameStateModel; // Suppress CS0219 warning
                var _p_UndoCommand_GameSessionModel = default(PixelFlow.Commands.UndoCommand).GameSessionModel;
                _ = _p_UndoCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_UndoCommand_LevelModel = default(PixelFlow.Commands.UndoCommand).LevelModel;
                _ = _p_UndoCommand_LevelModel; // Suppress CS0219 warning
                var _p_UndoCommand_SaveThrottler = default(PixelFlow.Commands.UndoCommand).SaveThrottler;
                _ = _p_UndoCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_UndoCommand_CrisisAdService = default(PixelFlow.Commands.UndoCommand).CrisisAdService;
                _ = _p_UndoCommand_CrisisAdService; // Suppress CS0219 warning
                var _p_UndoCommand_HapticService = default(PixelFlow.Commands.UndoCommand).HapticService;
                _ = _p_UndoCommand_HapticService; // Suppress CS0219 warning
                var _p_UndoCommand_PlayerPrefsService = default(PixelFlow.Commands.UndoCommand).PlayerPrefsService;
                _ = _p_UndoCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_UndoCommand_LoggerService = default(PixelFlow.Commands.UndoCommand).LoggerService;
                _ = _p_UndoCommand_LoggerService; // Suppress CS0219 warning
                var _p_UseHintCommand_HintModel = default(PixelFlow.Commands.UseHintCommand).HintModel;
                _ = _p_UseHintCommand_HintModel; // Suppress CS0219 warning
                var _p_UseHintCommand_GridModel = default(PixelFlow.Commands.UseHintCommand).GridModel;
                _ = _p_UseHintCommand_GridModel; // Suppress CS0219 warning
                var _p_UseHintCommand_LevelModel = default(PixelFlow.Commands.UseHintCommand).LevelModel;
                _ = _p_UseHintCommand_LevelModel; // Suppress CS0219 warning
                var _p_UseHintCommand_GameSessionModel = default(PixelFlow.Commands.UseHintCommand).GameSessionModel;
                _ = _p_UseHintCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_UseHintCommand_SignalBus = default(PixelFlow.Commands.UseHintCommand).SignalBus;
                _ = _p_UseHintCommand_SignalBus; // Suppress CS0219 warning
                var _p_UseHintCommand_PathService = default(PixelFlow.Commands.UseHintCommand).PathService;
                _ = _p_UseHintCommand_PathService; // Suppress CS0219 warning
                var _p_UseHintCommand_HintService = default(PixelFlow.Commands.UseHintCommand).HintService;
                _ = _p_UseHintCommand_HintService; // Suppress CS0219 warning
                var _p_UseHintCommand_HistoryService = default(PixelFlow.Commands.UseHintCommand).HistoryService;
                _ = _p_UseHintCommand_HistoryService; // Suppress CS0219 warning
                var _p_UseHintCommand_SaveThrottler = default(PixelFlow.Commands.UseHintCommand).SaveThrottler;
                _ = _p_UseHintCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_UseHintCommand_HapticService = default(PixelFlow.Commands.UseHintCommand).HapticService;
                _ = _p_UseHintCommand_HapticService; // Suppress CS0219 warning
                var _p_UseHintCommand_LoggerService = default(PixelFlow.Commands.UseHintCommand).LoggerService;
                _ = _p_UseHintCommand_LoggerService; // Suppress CS0219 warning
                var _p_UseHintCommand_PlayerPrefsService = default(PixelFlow.Commands.UseHintCommand).PlayerPrefsService;
                _ = _p_UseHintCommand_PlayerPrefsService; // Suppress CS0219 warning
            }
            #pragma warning restore 0162, 0169, 0414, 0219
        }
    }
}
