#define NEXUS_GENERATED_BINDER
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Nexus AOT Binder Code Generator.
//     Package Version: 0.4.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Nexus.Core;
using Nexus.Netcode;

namespace Nexus.Generated
{
    public static class NexusGeneratedBinder
    {

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]
        public static void Initialize()
        {
            NexusDI.RegisterInjector<Nexus.Core.Services.AudioService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.AudioRootProvider = di.Resolve<Nexus.Core.Services.IAudioRootProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.AudioService>(instance =>
            {
                instance.PlayerPrefsService = null;
                instance.AudioRootProvider = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.EconomyService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.NetworkValidator = di.Resolve<Nexus.Core.Services.INetworkEconomyValidator>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.EconomyService>(instance =>
            {
                instance.PlayerPrefsService = null;
                instance.NetworkValidator = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.FeedbackService>((instance, di) =>
            {
                instance.AudioService = di.Resolve<Nexus.Core.Services.IAudioService>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.FeedbackService>(instance =>
            {
                instance.AudioService = null;
                instance.HapticService = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.HapticService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.HapticService>(instance =>
            {
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.LocalizationService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.TableProvider = di.Resolve<Nexus.Core.Services.ILocalizationTableProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.LocalizationService>(instance =>
            {
                instance.PlayerPrefsService = null;
                instance.TableProvider = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.ProgressionService>((instance, di) =>
            {
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.ProgressionService>(instance =>
            {
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.SaveThrottler>((instance, di) =>
            {
                instance.TickService = di.Resolve<Nexus.Core.Services.ITickService>();
                instance.TimeProvider = di.Resolve<Nexus.Core.Services.ITimeProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.SaveThrottler>(instance =>
            {
                instance.TickService = null;
                instance.TimeProvider = null;
            });
            NexusDI.RegisterInjector<Nexus.Core.Services.WindowManager>((instance, di) =>
            {
                instance.AssetProvider = di.Resolve<Nexus.Core.Services.IUIAssetProvider>();
            });
            NexusDI.RegisterClearer<Nexus.Core.Services.WindowManager>(instance =>
            {
                instance.AssetProvider = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.DailyCrisisMediator>((instance, di) =>
            {
                instance.DailyCrisisModel = di.Resolve<PixelFlow.Models.IDailyCrisisModel>();
                instance.DailyCrisisService = di.Resolve<PixelFlow.Services.IDailyCrisisService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.DailyCrisisMediator>(instance =>
            {
                instance.DailyCrisisModel = null;
                instance.DailyCrisisService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.GridMediator>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.Logger = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.GridMediator>(instance =>
            {
                instance.GridModel = null;
                instance.SettingsModel = null;
                instance.Logger = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.GridView>((instance, di) =>
            {
                instance.CameraProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.GridView>(instance =>
            {
                instance.CameraProvider = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.HUDMediator>((instance, di) =>
            {
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.ProgressionService = di.Resolve<PixelFlow.Services.ILevelProgressionService>();
                instance.LocalizationService = di.Resolve<Nexus.Core.Services.ILocalizationService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.HUDMediator>(instance =>
            {
                instance.HintModel = null;
                instance.LevelModel = null;
                instance.SettingsModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.HistoryService = null;
                instance.ProgressionService = null;
                instance.LocalizationService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SettingsMediator>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SettingsMediator>(instance =>
            {
                instance.SettingsModel = null;
                instance.GameStateModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.SoundHandlerMediator>((instance, di) =>
            {
                instance.SoundModel = di.Resolve<PixelFlow.Models.ISoundModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.SoundHandlerMediator>(instance =>
            {
                instance.SoundModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.ThemeHandlerMediator>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.CameraProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.ThemeHandlerMediator>(instance =>
            {
                instance.SettingsModel = null;
                instance.CameraProvider = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Views.TutorialMediator>((instance, di) =>
            {
                instance.TutorialModel = di.Resolve<PixelFlow.Models.ITutorialModel>();
                instance.TutorialDriver = di.Resolve<PixelFlow.Services.ITutorialDriver>();
            });
            NexusDI.RegisterClearer<PixelFlow.Views.TutorialMediator>(instance =>
            {
                instance.TutorialModel = null;
                instance.TutorialDriver = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.AudioService>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.AudioService>(instance =>
            {
                instance.SettingsModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.CameraController>((instance, di) =>
            {
                instance.CameraProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.CameraController>(instance =>
            {
                instance.CameraProvider = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.CameraControllerMediator>((instance, di) =>
            {
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.CameraControllerMediator>(instance =>
            {
                instance.GameStateModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.CrisisAdService>((instance, di) =>
            {
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.CrisisAdService>(instance =>
            {
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.LevelModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.DailyCrisisService>((instance, di) =>
            {
                instance.DailyCrisisModel = di.Resolve<PixelFlow.Models.IDailyCrisisModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.DailyCrisisService>(instance =>
            {
                instance.DailyCrisisModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.GameplayTimerService>((instance, di) =>
            {
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.GameplayTimerService>(instance =>
            {
                instance.GameStateModel = null;
                instance.SignalBus = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.ObstacleService>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.ObstacleService>(instance =>
            {
                instance.GridModel = null;
                instance.SignalBus = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.PathService>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.PathService>(instance =>
            {
                instance.GridModel = null;
                instance.GameSessionModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.TutorialDriver>((instance, di) =>
            {
                instance.TutorialModel = di.Resolve<PixelFlow.Models.ITutorialModel>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.TutorialDriver>(instance =>
            {
                instance.TutorialModel = null;
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Services.VehicleSimulator>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.AudioService = di.Resolve<PixelFlow.Services.IAudioService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.CamProvider = di.Resolve<PixelFlow.Services.ICameraProvider>();
                instance.CrisisAdService = di.Resolve<PixelFlow.Services.ICrisisAdService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Services.VehicleSimulator>(instance =>
            {
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.HintModel = null;
                instance.HapticService = null;
                instance.AudioService = null;
                instance.ObstacleService = null;
                instance.SettingsModel = null;
                instance.LoggerService = null;
                instance.CamProvider = null;
                instance.CrisisAdService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.ChangeThemeCommand>((instance, di) =>
            {
                instance.SettingsModel = di.Resolve<PixelFlow.Models.ISettingsModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.ChangeThemeCommand>(instance =>
            {
                instance.SettingsModel = null;
                instance.SignalBus = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.CheckWinConditionCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.CheckWinConditionCommand>(instance =>
            {
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.HintModel = null;
                instance.SignalBus = null;
                instance.LoggerService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.LevelVictoryCompositeHandler>((instance, di) =>
            {
                instance.FeedbackService = di.Resolve<Nexus.Core.Services.IFeedbackService>();
                instance.Logger = di.Resolve<Nexus.Core.Services.ILoggerService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.LevelVictoryCompositeHandler>(instance =>
            {
                instance.FeedbackService = null;
                instance.Logger = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.LoadLevelCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.TutorialDriver = di.Resolve<PixelFlow.Services.ITutorialDriver>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.LevelLoaderService = di.Resolve<PixelFlow.Services.ILevelLoaderService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.LoadLevelCommand>(instance =>
            {
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.HintModel = null;
                instance.SignalBus = null;
                instance.HistoryService = null;
                instance.ObstacleService = null;
                instance.SaveThrottler = null;
                instance.TutorialDriver = null;
                instance.LoggerService = null;
                instance.PlayerPrefsService = null;
                instance.LevelLoaderService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.PauseSimulationCommand>((instance, di) =>
            {
                instance.VehicleSimulator = di.Resolve<PixelFlow.Services.IVehicleSimulator>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.PauseSimulationCommand>(instance =>
            {
                instance.VehicleSimulator = null;
                instance.GameStateModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.PlaceViaductCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.PlaceViaductCommand>(instance =>
            {
                instance.GridModel = null;
                instance.GameSessionModel = null;
                instance.GameStateModel = null;
                instance.SignalBus = null;
                instance.HistoryService = null;
                instance.SaveThrottler = null;
                instance.LevelModel = null;
                instance.HapticService = null;
                instance.LoggerService = null;
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.ProcessInputCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.SoundModel = di.Resolve<PixelFlow.Models.ISoundModel>();
                instance.PathService = di.Resolve<PixelFlow.Services.IPathService>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.ObstacleService = di.Resolve<PixelFlow.Services.IObstacleService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.ProcessInputCommand>(instance =>
            {
                instance.GridModel = null;
                instance.SignalBus = null;
                instance.SoundModel = null;
                instance.PathService = null;
                instance.GameStateModel = null;
                instance.HistoryService = null;
                instance.GameSessionModel = null;
                instance.LevelModel = null;
                instance.SaveThrottler = null;
                instance.HapticService = null;
                instance.ObstacleService = null;
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.RedoCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.RedoCommand>(instance =>
            {
                instance.GridModel = null;
                instance.HistoryService = null;
                instance.SignalBus = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.SaveProgressCommand>((instance, di) =>
            {
                instance.ProgressModel = di.Resolve<PixelFlow.Models.IProgressModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.SaveProgressCommand>(instance =>
            {
                instance.ProgressModel = null;
                instance.LevelModel = null;
                instance.SignalBus = null;
                instance.PlayerPrefsService = null;
                instance.LoggerService = null;
                instance.HintModel = null;
                instance.GameSessionModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.StartSimulationCommand>((instance, di) =>
            {
                instance.VehicleSimulator = di.Resolve<PixelFlow.Services.IVehicleSimulator>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.StartSimulationCommand>(instance =>
            {
                instance.VehicleSimulator = null;
                instance.GameStateModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.TimerCommand>((instance, di) =>
            {
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.TimerCommand>(instance =>
            {
                instance.GameSessionModel = null;
                instance.GameStateModel = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.UndoCommand>((instance, di) =>
            {
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.GameStateModel = di.Resolve<PixelFlow.Models.IGameStateModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.CrisisAdService = di.Resolve<PixelFlow.Services.ICrisisAdService>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.UndoCommand>(instance =>
            {
                instance.GridModel = null;
                instance.HistoryService = null;
                instance.SignalBus = null;
                instance.GameStateModel = null;
                instance.GameSessionModel = null;
                instance.LevelModel = null;
                instance.SaveThrottler = null;
                instance.CrisisAdService = null;
                instance.HapticService = null;
                instance.PlayerPrefsService = null;
            });
            NexusDI.RegisterInjector<PixelFlow.Commands.UseHintCommand>((instance, di) =>
            {
                instance.HintModel = di.Resolve<PixelFlow.Models.IHintModel>();
                instance.GridModel = di.Resolve<PixelFlow.Models.IGridModel>();
                instance.LevelModel = di.Resolve<PixelFlow.Models.ILevelModel>();
                instance.GameSessionModel = di.Resolve<PixelFlow.Models.IGameSessionModel>();
                instance.SignalBus = di.Resolve<Nexus.Core.ISignalBus>();
                instance.PathService = di.Resolve<PixelFlow.Services.IPathService>();
                instance.HintService = di.Resolve<PixelFlow.Services.IHintService>();
                instance.HistoryService = di.Resolve<PixelFlow.Services.IGameHistoryService>();
                instance.SaveThrottler = di.Resolve<Nexus.Core.Services.ISaveThrottler>();
                instance.HapticService = di.Resolve<Nexus.Core.Services.IHapticService>();
                instance.LoggerService = di.Resolve<Nexus.Core.Services.ILoggerService>();
                instance.PlayerPrefsService = di.Resolve<Nexus.Core.Services.IPlayerPrefsService>();
            });
            NexusDI.RegisterClearer<PixelFlow.Commands.UseHintCommand>(instance =>
            {
                instance.HintModel = null;
                instance.GridModel = null;
                instance.LevelModel = null;
                instance.GameSessionModel = null;
                instance.SignalBus = null;
                instance.PathService = null;
                instance.HintService = null;
                instance.HistoryService = null;
                instance.SaveThrottler = null;
                instance.HapticService = null;
                instance.LoggerService = null;
                instance.PlayerPrefsService = null;
            });
        }

        // Forces IL2CPP to preserve members that are injected
        public static void PreserveMembers()
        {
            #pragma warning disable 0162, 0169, 0414, 0219
            if (false)
            {
                var _p_AudioService_PlayerPrefsService = default(Nexus.Core.Services.AudioService).PlayerPrefsService;
                _ = _p_AudioService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_AudioService_AudioRootProvider = default(Nexus.Core.Services.AudioService).AudioRootProvider;
                _ = _p_AudioService_AudioRootProvider; // Suppress CS0219 warning
                var _p_EconomyService_PlayerPrefsService = default(Nexus.Core.Services.EconomyService).PlayerPrefsService;
                _ = _p_EconomyService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_EconomyService_NetworkValidator = default(Nexus.Core.Services.EconomyService).NetworkValidator;
                _ = _p_EconomyService_NetworkValidator; // Suppress CS0219 warning
                var _p_FeedbackService_AudioService = default(Nexus.Core.Services.FeedbackService).AudioService;
                _ = _p_FeedbackService_AudioService; // Suppress CS0219 warning
                var _p_FeedbackService_HapticService = default(Nexus.Core.Services.FeedbackService).HapticService;
                _ = _p_FeedbackService_HapticService; // Suppress CS0219 warning
                var _p_HapticService_PlayerPrefsService = default(Nexus.Core.Services.HapticService).PlayerPrefsService;
                _ = _p_HapticService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_LocalizationService_PlayerPrefsService = default(Nexus.Core.Services.LocalizationService).PlayerPrefsService;
                _ = _p_LocalizationService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_LocalizationService_TableProvider = default(Nexus.Core.Services.LocalizationService).TableProvider;
                _ = _p_LocalizationService_TableProvider; // Suppress CS0219 warning
                var _p_ProgressionService_PlayerPrefsService = default(Nexus.Core.Services.ProgressionService).PlayerPrefsService;
                _ = _p_ProgressionService_PlayerPrefsService; // Suppress CS0219 warning
                var _p_SaveThrottler_TickService = default(Nexus.Core.Services.SaveThrottler).TickService;
                _ = _p_SaveThrottler_TickService; // Suppress CS0219 warning
                var _p_SaveThrottler_TimeProvider = default(Nexus.Core.Services.SaveThrottler).TimeProvider;
                _ = _p_SaveThrottler_TimeProvider; // Suppress CS0219 warning
                var _p_WindowManager_AssetProvider = default(Nexus.Core.Services.WindowManager).AssetProvider;
                _ = _p_WindowManager_AssetProvider; // Suppress CS0219 warning
                var _p_DailyCrisisMediator_DailyCrisisModel = default(PixelFlow.Views.DailyCrisisMediator).DailyCrisisModel;
                _ = _p_DailyCrisisMediator_DailyCrisisModel; // Suppress CS0219 warning
                var _p_DailyCrisisMediator_DailyCrisisService = default(PixelFlow.Views.DailyCrisisMediator).DailyCrisisService;
                _ = _p_DailyCrisisMediator_DailyCrisisService; // Suppress CS0219 warning
                var _p_GridMediator_GridModel = default(PixelFlow.Views.GridMediator).GridModel;
                _ = _p_GridMediator_GridModel; // Suppress CS0219 warning
                var _p_GridMediator_SettingsModel = default(PixelFlow.Views.GridMediator).SettingsModel;
                _ = _p_GridMediator_SettingsModel; // Suppress CS0219 warning
                var _p_GridMediator_Logger = default(PixelFlow.Views.GridMediator).Logger;
                _ = _p_GridMediator_Logger; // Suppress CS0219 warning
                var _p_GridView_CameraProvider = default(PixelFlow.Views.GridView).CameraProvider;
                _ = _p_GridView_CameraProvider; // Suppress CS0219 warning
                var _p_HUDMediator_HintModel = default(PixelFlow.Views.HUDMediator).HintModel;
                _ = _p_HUDMediator_HintModel; // Suppress CS0219 warning
                var _p_HUDMediator_LevelModel = default(PixelFlow.Views.HUDMediator).LevelModel;
                _ = _p_HUDMediator_LevelModel; // Suppress CS0219 warning
                var _p_HUDMediator_SettingsModel = default(PixelFlow.Views.HUDMediator).SettingsModel;
                _ = _p_HUDMediator_SettingsModel; // Suppress CS0219 warning
                var _p_HUDMediator_GameStateModel = default(PixelFlow.Views.HUDMediator).GameStateModel;
                _ = _p_HUDMediator_GameStateModel; // Suppress CS0219 warning
                var _p_HUDMediator_GameSessionModel = default(PixelFlow.Views.HUDMediator).GameSessionModel;
                _ = _p_HUDMediator_GameSessionModel; // Suppress CS0219 warning
                var _p_HUDMediator_HistoryService = default(PixelFlow.Views.HUDMediator).HistoryService;
                _ = _p_HUDMediator_HistoryService; // Suppress CS0219 warning
                var _p_HUDMediator_ProgressionService = default(PixelFlow.Views.HUDMediator).ProgressionService;
                _ = _p_HUDMediator_ProgressionService; // Suppress CS0219 warning
                var _p_HUDMediator_LocalizationService = default(PixelFlow.Views.HUDMediator).LocalizationService;
                _ = _p_HUDMediator_LocalizationService; // Suppress CS0219 warning
                var _p_SettingsMediator_SettingsModel = default(PixelFlow.Views.SettingsMediator).SettingsModel;
                _ = _p_SettingsMediator_SettingsModel; // Suppress CS0219 warning
                var _p_SettingsMediator_GameStateModel = default(PixelFlow.Views.SettingsMediator).GameStateModel;
                _ = _p_SettingsMediator_GameStateModel; // Suppress CS0219 warning
                var _p_SoundHandlerMediator_SoundModel = default(PixelFlow.Views.SoundHandlerMediator).SoundModel;
                _ = _p_SoundHandlerMediator_SoundModel; // Suppress CS0219 warning
                var _p_ThemeHandlerMediator_SettingsModel = default(PixelFlow.Views.ThemeHandlerMediator).SettingsModel;
                _ = _p_ThemeHandlerMediator_SettingsModel; // Suppress CS0219 warning
                var _p_ThemeHandlerMediator_CameraProvider = default(PixelFlow.Views.ThemeHandlerMediator).CameraProvider;
                _ = _p_ThemeHandlerMediator_CameraProvider; // Suppress CS0219 warning
                var _p_TutorialMediator_TutorialModel = default(PixelFlow.Views.TutorialMediator).TutorialModel;
                _ = _p_TutorialMediator_TutorialModel; // Suppress CS0219 warning
                var _p_TutorialMediator_TutorialDriver = default(PixelFlow.Views.TutorialMediator).TutorialDriver;
                _ = _p_TutorialMediator_TutorialDriver; // Suppress CS0219 warning
                var _p_AudioService_SettingsModel = default(PixelFlow.Services.AudioService).SettingsModel;
                _ = _p_AudioService_SettingsModel; // Suppress CS0219 warning
                var _p_CameraController_CameraProvider = default(PixelFlow.Services.CameraController).CameraProvider;
                _ = _p_CameraController_CameraProvider; // Suppress CS0219 warning
                var _p_CameraControllerMediator_GameStateModel = default(PixelFlow.Services.CameraControllerMediator).GameStateModel;
                _ = _p_CameraControllerMediator_GameStateModel; // Suppress CS0219 warning
                var _p_CrisisAdService_GameSessionModel = default(PixelFlow.Services.CrisisAdService).GameSessionModel;
                _ = _p_CrisisAdService_GameSessionModel; // Suppress CS0219 warning
                var _p_CrisisAdService_SignalBus = default(PixelFlow.Services.CrisisAdService).SignalBus;
                _ = _p_CrisisAdService_SignalBus; // Suppress CS0219 warning
                var _p_CrisisAdService_LevelModel = default(PixelFlow.Services.CrisisAdService).LevelModel;
                _ = _p_CrisisAdService_LevelModel; // Suppress CS0219 warning
                var _p_DailyCrisisService_DailyCrisisModel = default(PixelFlow.Services.DailyCrisisService).DailyCrisisModel;
                _ = _p_DailyCrisisService_DailyCrisisModel; // Suppress CS0219 warning
                var _p_GameplayTimerService_GameStateModel = default(PixelFlow.Services.GameplayTimerService).GameStateModel;
                _ = _p_GameplayTimerService_GameStateModel; // Suppress CS0219 warning
                var _p_GameplayTimerService_SignalBus = default(PixelFlow.Services.GameplayTimerService).SignalBus;
                _ = _p_GameplayTimerService_SignalBus; // Suppress CS0219 warning
                var _p_ObstacleService_GridModel = default(PixelFlow.Services.ObstacleService).GridModel;
                _ = _p_ObstacleService_GridModel; // Suppress CS0219 warning
                var _p_ObstacleService_SignalBus = default(PixelFlow.Services.ObstacleService).SignalBus;
                _ = _p_ObstacleService_SignalBus; // Suppress CS0219 warning
                var _p_PathService_GridModel = default(PixelFlow.Services.PathService).GridModel;
                _ = _p_PathService_GridModel; // Suppress CS0219 warning
                var _p_PathService_GameSessionModel = default(PixelFlow.Services.PathService).GameSessionModel;
                _ = _p_PathService_GameSessionModel; // Suppress CS0219 warning
                var _p_TutorialDriver_TutorialModel = default(PixelFlow.Services.TutorialDriver).TutorialModel;
                _ = _p_TutorialDriver_TutorialModel; // Suppress CS0219 warning
                var _p_TutorialDriver_PlayerPrefsService = default(PixelFlow.Services.TutorialDriver).PlayerPrefsService;
                _ = _p_TutorialDriver_PlayerPrefsService; // Suppress CS0219 warning
                var _p_VehicleSimulator_GridModel = default(PixelFlow.Services.VehicleSimulator).GridModel;
                _ = _p_VehicleSimulator_GridModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_LevelModel = default(PixelFlow.Services.VehicleSimulator).LevelModel;
                _ = _p_VehicleSimulator_LevelModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_GameStateModel = default(PixelFlow.Services.VehicleSimulator).GameStateModel;
                _ = _p_VehicleSimulator_GameStateModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_GameSessionModel = default(PixelFlow.Services.VehicleSimulator).GameSessionModel;
                _ = _p_VehicleSimulator_GameSessionModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_SignalBus = default(PixelFlow.Services.VehicleSimulator).SignalBus;
                _ = _p_VehicleSimulator_SignalBus; // Suppress CS0219 warning
                var _p_VehicleSimulator_HintModel = default(PixelFlow.Services.VehicleSimulator).HintModel;
                _ = _p_VehicleSimulator_HintModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_HapticService = default(PixelFlow.Services.VehicleSimulator).HapticService;
                _ = _p_VehicleSimulator_HapticService; // Suppress CS0219 warning
                var _p_VehicleSimulator_AudioService = default(PixelFlow.Services.VehicleSimulator).AudioService;
                _ = _p_VehicleSimulator_AudioService; // Suppress CS0219 warning
                var _p_VehicleSimulator_ObstacleService = default(PixelFlow.Services.VehicleSimulator).ObstacleService;
                _ = _p_VehicleSimulator_ObstacleService; // Suppress CS0219 warning
                var _p_VehicleSimulator_SettingsModel = default(PixelFlow.Services.VehicleSimulator).SettingsModel;
                _ = _p_VehicleSimulator_SettingsModel; // Suppress CS0219 warning
                var _p_VehicleSimulator_LoggerService = default(PixelFlow.Services.VehicleSimulator).LoggerService;
                _ = _p_VehicleSimulator_LoggerService; // Suppress CS0219 warning
                var _p_VehicleSimulator_CamProvider = default(PixelFlow.Services.VehicleSimulator).CamProvider;
                _ = _p_VehicleSimulator_CamProvider; // Suppress CS0219 warning
                var _p_VehicleSimulator_CrisisAdService = default(PixelFlow.Services.VehicleSimulator).CrisisAdService;
                _ = _p_VehicleSimulator_CrisisAdService; // Suppress CS0219 warning
                var _p_ChangeThemeCommand_SettingsModel = default(PixelFlow.Commands.ChangeThemeCommand).SettingsModel;
                _ = _p_ChangeThemeCommand_SettingsModel; // Suppress CS0219 warning
                var _p_ChangeThemeCommand_SignalBus = default(PixelFlow.Commands.ChangeThemeCommand).SignalBus;
                _ = _p_ChangeThemeCommand_SignalBus; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_GridModel = default(PixelFlow.Commands.CheckWinConditionCommand).GridModel;
                _ = _p_CheckWinConditionCommand_GridModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_LevelModel = default(PixelFlow.Commands.CheckWinConditionCommand).LevelModel;
                _ = _p_CheckWinConditionCommand_LevelModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_GameStateModel = default(PixelFlow.Commands.CheckWinConditionCommand).GameStateModel;
                _ = _p_CheckWinConditionCommand_GameStateModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_GameSessionModel = default(PixelFlow.Commands.CheckWinConditionCommand).GameSessionModel;
                _ = _p_CheckWinConditionCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_HintModel = default(PixelFlow.Commands.CheckWinConditionCommand).HintModel;
                _ = _p_CheckWinConditionCommand_HintModel; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_SignalBus = default(PixelFlow.Commands.CheckWinConditionCommand).SignalBus;
                _ = _p_CheckWinConditionCommand_SignalBus; // Suppress CS0219 warning
                var _p_CheckWinConditionCommand_LoggerService = default(PixelFlow.Commands.CheckWinConditionCommand).LoggerService;
                _ = _p_CheckWinConditionCommand_LoggerService; // Suppress CS0219 warning
                var _p_LevelVictoryCompositeHandler_FeedbackService = default(PixelFlow.Commands.LevelVictoryCompositeHandler).FeedbackService;
                _ = _p_LevelVictoryCompositeHandler_FeedbackService; // Suppress CS0219 warning
                var _p_LevelVictoryCompositeHandler_Logger = default(PixelFlow.Commands.LevelVictoryCompositeHandler).Logger;
                _ = _p_LevelVictoryCompositeHandler_Logger; // Suppress CS0219 warning
                var _p_LoadLevelCommand_GridModel = default(PixelFlow.Commands.LoadLevelCommand).GridModel;
                _ = _p_LoadLevelCommand_GridModel; // Suppress CS0219 warning
                var _p_LoadLevelCommand_LevelModel = default(PixelFlow.Commands.LoadLevelCommand).LevelModel;
                _ = _p_LoadLevelCommand_LevelModel; // Suppress CS0219 warning
                var _p_LoadLevelCommand_GameStateModel = default(PixelFlow.Commands.LoadLevelCommand).GameStateModel;
                _ = _p_LoadLevelCommand_GameStateModel; // Suppress CS0219 warning
                var _p_LoadLevelCommand_GameSessionModel = default(PixelFlow.Commands.LoadLevelCommand).GameSessionModel;
                _ = _p_LoadLevelCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_LoadLevelCommand_HintModel = default(PixelFlow.Commands.LoadLevelCommand).HintModel;
                _ = _p_LoadLevelCommand_HintModel; // Suppress CS0219 warning
                var _p_LoadLevelCommand_SignalBus = default(PixelFlow.Commands.LoadLevelCommand).SignalBus;
                _ = _p_LoadLevelCommand_SignalBus; // Suppress CS0219 warning
                var _p_LoadLevelCommand_HistoryService = default(PixelFlow.Commands.LoadLevelCommand).HistoryService;
                _ = _p_LoadLevelCommand_HistoryService; // Suppress CS0219 warning
                var _p_LoadLevelCommand_ObstacleService = default(PixelFlow.Commands.LoadLevelCommand).ObstacleService;
                _ = _p_LoadLevelCommand_ObstacleService; // Suppress CS0219 warning
                var _p_LoadLevelCommand_SaveThrottler = default(PixelFlow.Commands.LoadLevelCommand).SaveThrottler;
                _ = _p_LoadLevelCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_LoadLevelCommand_TutorialDriver = default(PixelFlow.Commands.LoadLevelCommand).TutorialDriver;
                _ = _p_LoadLevelCommand_TutorialDriver; // Suppress CS0219 warning
                var _p_LoadLevelCommand_LoggerService = default(PixelFlow.Commands.LoadLevelCommand).LoggerService;
                _ = _p_LoadLevelCommand_LoggerService; // Suppress CS0219 warning
                var _p_LoadLevelCommand_PlayerPrefsService = default(PixelFlow.Commands.LoadLevelCommand).PlayerPrefsService;
                _ = _p_LoadLevelCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_LoadLevelCommand_LevelLoaderService = default(PixelFlow.Commands.LoadLevelCommand).LevelLoaderService;
                _ = _p_LoadLevelCommand_LevelLoaderService; // Suppress CS0219 warning
                var _p_PauseSimulationCommand_VehicleSimulator = default(PixelFlow.Commands.PauseSimulationCommand).VehicleSimulator;
                _ = _p_PauseSimulationCommand_VehicleSimulator; // Suppress CS0219 warning
                var _p_PauseSimulationCommand_GameStateModel = default(PixelFlow.Commands.PauseSimulationCommand).GameStateModel;
                _ = _p_PauseSimulationCommand_GameStateModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_GridModel = default(PixelFlow.Commands.PlaceViaductCommand).GridModel;
                _ = _p_PlaceViaductCommand_GridModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_GameSessionModel = default(PixelFlow.Commands.PlaceViaductCommand).GameSessionModel;
                _ = _p_PlaceViaductCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_GameStateModel = default(PixelFlow.Commands.PlaceViaductCommand).GameStateModel;
                _ = _p_PlaceViaductCommand_GameStateModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_SignalBus = default(PixelFlow.Commands.PlaceViaductCommand).SignalBus;
                _ = _p_PlaceViaductCommand_SignalBus; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_HistoryService = default(PixelFlow.Commands.PlaceViaductCommand).HistoryService;
                _ = _p_PlaceViaductCommand_HistoryService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_SaveThrottler = default(PixelFlow.Commands.PlaceViaductCommand).SaveThrottler;
                _ = _p_PlaceViaductCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_LevelModel = default(PixelFlow.Commands.PlaceViaductCommand).LevelModel;
                _ = _p_PlaceViaductCommand_LevelModel; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_HapticService = default(PixelFlow.Commands.PlaceViaductCommand).HapticService;
                _ = _p_PlaceViaductCommand_HapticService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_LoggerService = default(PixelFlow.Commands.PlaceViaductCommand).LoggerService;
                _ = _p_PlaceViaductCommand_LoggerService; // Suppress CS0219 warning
                var _p_PlaceViaductCommand_PlayerPrefsService = default(PixelFlow.Commands.PlaceViaductCommand).PlayerPrefsService;
                _ = _p_PlaceViaductCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_GridModel = default(PixelFlow.Commands.ProcessInputCommand).GridModel;
                _ = _p_ProcessInputCommand_GridModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_SignalBus = default(PixelFlow.Commands.ProcessInputCommand).SignalBus;
                _ = _p_ProcessInputCommand_SignalBus; // Suppress CS0219 warning
                var _p_ProcessInputCommand_SoundModel = default(PixelFlow.Commands.ProcessInputCommand).SoundModel;
                _ = _p_ProcessInputCommand_SoundModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_PathService = default(PixelFlow.Commands.ProcessInputCommand).PathService;
                _ = _p_ProcessInputCommand_PathService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_GameStateModel = default(PixelFlow.Commands.ProcessInputCommand).GameStateModel;
                _ = _p_ProcessInputCommand_GameStateModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_HistoryService = default(PixelFlow.Commands.ProcessInputCommand).HistoryService;
                _ = _p_ProcessInputCommand_HistoryService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_GameSessionModel = default(PixelFlow.Commands.ProcessInputCommand).GameSessionModel;
                _ = _p_ProcessInputCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_LevelModel = default(PixelFlow.Commands.ProcessInputCommand).LevelModel;
                _ = _p_ProcessInputCommand_LevelModel; // Suppress CS0219 warning
                var _p_ProcessInputCommand_SaveThrottler = default(PixelFlow.Commands.ProcessInputCommand).SaveThrottler;
                _ = _p_ProcessInputCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_ProcessInputCommand_HapticService = default(PixelFlow.Commands.ProcessInputCommand).HapticService;
                _ = _p_ProcessInputCommand_HapticService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_ObstacleService = default(PixelFlow.Commands.ProcessInputCommand).ObstacleService;
                _ = _p_ProcessInputCommand_ObstacleService; // Suppress CS0219 warning
                var _p_ProcessInputCommand_PlayerPrefsService = default(PixelFlow.Commands.ProcessInputCommand).PlayerPrefsService;
                _ = _p_ProcessInputCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_RedoCommand_GridModel = default(PixelFlow.Commands.RedoCommand).GridModel;
                _ = _p_RedoCommand_GridModel; // Suppress CS0219 warning
                var _p_RedoCommand_HistoryService = default(PixelFlow.Commands.RedoCommand).HistoryService;
                _ = _p_RedoCommand_HistoryService; // Suppress CS0219 warning
                var _p_RedoCommand_SignalBus = default(PixelFlow.Commands.RedoCommand).SignalBus;
                _ = _p_RedoCommand_SignalBus; // Suppress CS0219 warning
                var _p_RedoCommand_GameStateModel = default(PixelFlow.Commands.RedoCommand).GameStateModel;
                _ = _p_RedoCommand_GameStateModel; // Suppress CS0219 warning
                var _p_RedoCommand_GameSessionModel = default(PixelFlow.Commands.RedoCommand).GameSessionModel;
                _ = _p_RedoCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_ProgressModel = default(PixelFlow.Commands.SaveProgressCommand).ProgressModel;
                _ = _p_SaveProgressCommand_ProgressModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_LevelModel = default(PixelFlow.Commands.SaveProgressCommand).LevelModel;
                _ = _p_SaveProgressCommand_LevelModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_SignalBus = default(PixelFlow.Commands.SaveProgressCommand).SignalBus;
                _ = _p_SaveProgressCommand_SignalBus; // Suppress CS0219 warning
                var _p_SaveProgressCommand_PlayerPrefsService = default(PixelFlow.Commands.SaveProgressCommand).PlayerPrefsService;
                _ = _p_SaveProgressCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_SaveProgressCommand_LoggerService = default(PixelFlow.Commands.SaveProgressCommand).LoggerService;
                _ = _p_SaveProgressCommand_LoggerService; // Suppress CS0219 warning
                var _p_SaveProgressCommand_HintModel = default(PixelFlow.Commands.SaveProgressCommand).HintModel;
                _ = _p_SaveProgressCommand_HintModel; // Suppress CS0219 warning
                var _p_SaveProgressCommand_GameSessionModel = default(PixelFlow.Commands.SaveProgressCommand).GameSessionModel;
                _ = _p_SaveProgressCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_StartSimulationCommand_VehicleSimulator = default(PixelFlow.Commands.StartSimulationCommand).VehicleSimulator;
                _ = _p_StartSimulationCommand_VehicleSimulator; // Suppress CS0219 warning
                var _p_StartSimulationCommand_GameStateModel = default(PixelFlow.Commands.StartSimulationCommand).GameStateModel;
                _ = _p_StartSimulationCommand_GameStateModel; // Suppress CS0219 warning
                var _p_TimerCommand_GameSessionModel = default(PixelFlow.Commands.TimerCommand).GameSessionModel;
                _ = _p_TimerCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_TimerCommand_GameStateModel = default(PixelFlow.Commands.TimerCommand).GameStateModel;
                _ = _p_TimerCommand_GameStateModel; // Suppress CS0219 warning
                var _p_UndoCommand_GridModel = default(PixelFlow.Commands.UndoCommand).GridModel;
                _ = _p_UndoCommand_GridModel; // Suppress CS0219 warning
                var _p_UndoCommand_HistoryService = default(PixelFlow.Commands.UndoCommand).HistoryService;
                _ = _p_UndoCommand_HistoryService; // Suppress CS0219 warning
                var _p_UndoCommand_SignalBus = default(PixelFlow.Commands.UndoCommand).SignalBus;
                _ = _p_UndoCommand_SignalBus; // Suppress CS0219 warning
                var _p_UndoCommand_GameStateModel = default(PixelFlow.Commands.UndoCommand).GameStateModel;
                _ = _p_UndoCommand_GameStateModel; // Suppress CS0219 warning
                var _p_UndoCommand_GameSessionModel = default(PixelFlow.Commands.UndoCommand).GameSessionModel;
                _ = _p_UndoCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_UndoCommand_LevelModel = default(PixelFlow.Commands.UndoCommand).LevelModel;
                _ = _p_UndoCommand_LevelModel; // Suppress CS0219 warning
                var _p_UndoCommand_SaveThrottler = default(PixelFlow.Commands.UndoCommand).SaveThrottler;
                _ = _p_UndoCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_UndoCommand_CrisisAdService = default(PixelFlow.Commands.UndoCommand).CrisisAdService;
                _ = _p_UndoCommand_CrisisAdService; // Suppress CS0219 warning
                var _p_UndoCommand_HapticService = default(PixelFlow.Commands.UndoCommand).HapticService;
                _ = _p_UndoCommand_HapticService; // Suppress CS0219 warning
                var _p_UndoCommand_PlayerPrefsService = default(PixelFlow.Commands.UndoCommand).PlayerPrefsService;
                _ = _p_UndoCommand_PlayerPrefsService; // Suppress CS0219 warning
                var _p_UseHintCommand_HintModel = default(PixelFlow.Commands.UseHintCommand).HintModel;
                _ = _p_UseHintCommand_HintModel; // Suppress CS0219 warning
                var _p_UseHintCommand_GridModel = default(PixelFlow.Commands.UseHintCommand).GridModel;
                _ = _p_UseHintCommand_GridModel; // Suppress CS0219 warning
                var _p_UseHintCommand_LevelModel = default(PixelFlow.Commands.UseHintCommand).LevelModel;
                _ = _p_UseHintCommand_LevelModel; // Suppress CS0219 warning
                var _p_UseHintCommand_GameSessionModel = default(PixelFlow.Commands.UseHintCommand).GameSessionModel;
                _ = _p_UseHintCommand_GameSessionModel; // Suppress CS0219 warning
                var _p_UseHintCommand_SignalBus = default(PixelFlow.Commands.UseHintCommand).SignalBus;
                _ = _p_UseHintCommand_SignalBus; // Suppress CS0219 warning
                var _p_UseHintCommand_PathService = default(PixelFlow.Commands.UseHintCommand).PathService;
                _ = _p_UseHintCommand_PathService; // Suppress CS0219 warning
                var _p_UseHintCommand_HintService = default(PixelFlow.Commands.UseHintCommand).HintService;
                _ = _p_UseHintCommand_HintService; // Suppress CS0219 warning
                var _p_UseHintCommand_HistoryService = default(PixelFlow.Commands.UseHintCommand).HistoryService;
                _ = _p_UseHintCommand_HistoryService; // Suppress CS0219 warning
                var _p_UseHintCommand_SaveThrottler = default(PixelFlow.Commands.UseHintCommand).SaveThrottler;
                _ = _p_UseHintCommand_SaveThrottler; // Suppress CS0219 warning
                var _p_UseHintCommand_HapticService = default(PixelFlow.Commands.UseHintCommand).HapticService;
                _ = _p_UseHintCommand_HapticService; // Suppress CS0219 warning
                var _p_UseHintCommand_LoggerService = default(PixelFlow.Commands.UseHintCommand).LoggerService;
                _ = _p_UseHintCommand_LoggerService; // Suppress CS0219 warning
                var _p_UseHintCommand_PlayerPrefsService = default(PixelFlow.Commands.UseHintCommand).PlayerPrefsService;
                _ = _p_UseHintCommand_PlayerPrefsService; // Suppress CS0219 warning
            }
            #pragma warning restore 0162, 0169, 0414, 0219
        }
    }
}
